### ISSUE TITLE
review + branch protections

### ISSUE THREAD

**Issue by escapewindow** [mozilla-releng/adhoc-signing#1]
Let's get a repo-level review + branch protections set before we use this repo for real.

**Comment by escapewindow** [comment]
I added branch protections for master. Callek is going to do repo review :)

**Comment by Callek** [comment]
Other than the few comments I added on commits in the repo, I have nothing blocking.

Those comments are mostly nits!

**Comment by escapewindow** [comment]
Thanks! I opened #4 -- let's land that, then let's see if the docs are informative enough for you to create a PR for the mar?
